package es.ull.project.domain.valueobject.demand;


import java.util.Objects;

/**
 * WasteDemand
 * 
 * Represents the amount of waste generated by a container or required by a service.
 * This is a mandatory value object in the domain.
 */
public final class WasteDemand {

    private static final String ERROR_DEMAND_NEGATIVE = "Waste demand cannot be negative";

    /**
     * Waste demand value (e.g., in tons/day or tons/year).
     */
    private final double value;

    /**
     * Optional unit for the waste demand (e.g., "tons/day", "tons/year").
     */
    private final String unit;

    /**
     * Creates a new WasteDemand with value and optional unit.
     * 
     * @param value Waste demand value. Must be ≥ 0.
     * @param unit  Optional unit of measurement.
     */
    public WasteDemand(double value, String unit) {
        this.validateValue(value);
        this.value = value;
        this.unit = (unit == null || unit.isEmpty()) ? "tons/day" : unit;
    }

    public WasteDemand(double value) {
        this.validateValue(value);
        this.value = value;
        this.unit = "tons/day";
    }

    private void validateValue(double value) {
        if (value < 0) {
            throw new IllegalArgumentException(ERROR_DEMAND_NEGATIVE);
        }
    }

    /**
     * Returns the waste demand value.
     * 
     * @return Waste demand.
     */
    public double getValue() {
        return this.value;
    }

    /**
     * Returns the unit of measurement.
     * 
     * @return Unit of waste demand.
     */
    public String getUnit() {
        return this.unit;
    }

    /**
     * Returns a new WasteDemand with a new value.
     * 
     * @param newValue New waste demand value.
     * @return New WasteDemand object.
     */
    public WasteDemand setValue(double newValue) {
        return new WasteDemand(newValue, this.unit);
    }

    /**
     * Returns a new WasteDemand with a new unit.
     * 
     * @param newUnit New unit of measurement.
     * @return New WasteDemand object.
     */
    public WasteDemand setUnit(String newUnit) {
        return new WasteDemand(this.value, newUnit);
    }

    @Override
    public boolean equals(Object otherObject) {
        if (this == otherObject) {
            return true;
        }
        if (otherObject == null) {
            return false;
        }
        if (this.getClass() != otherObject.getClass()) {
            return false;
        }
        WasteDemand otherWasteDemand = (WasteDemand) otherObject;
        return Double.compare(this.value, otherWasteDemand.value) == 0 &&
            this.unit.equals(otherWasteDemand.unit);
    }
    
    /**
     * Adds two WasteDemand objects with the same unit.
     * 
     * @param other Other WasteDemand to add.
     * @return New WasteDemand representing the sum.
     */
    public WasteDemand add(WasteDemand other) {
        if (other == null) {
            throw new IllegalArgumentException("Other WasteDemand cannot be null");
        }
        if (!this.unit.equals(other.unit)) {
            throw new IllegalArgumentException("Units must be the same to add WasteDemands");
        }
        return new WasteDemand(this.value + other.value, this.unit);
    }

    /**
        * Compares if this WasteDemand is greater than another WasteDemand with the same unit.
        * 
        * @param other Other WasteDemand to compare.
        * @return True if this WasteDemand is greater, false otherwise.
        * 
     */
    public boolean greaterThan(WasteDemand other) {
        if (other == null) {
            throw new IllegalArgumentException("Other WasteDemand cannot be null");
        }
        if (!this.unit.equals(other.unit)) {
            throw new IllegalArgumentException("Units must be the same to compare WasteDemands");
        }
        return this.value > other.value;
    }

    /**
        * Compares if this WasteDemand is greater than a Capacity with the same unit.
        * @param capacity Capacity to compare.  
        * @return True if this WasteDemand is greater, false otherwise.
     */
    public boolean greaterThan(Capacity capacity) {
        if (capacity == null) {
            throw new IllegalArgumentException("Capacity cannot be null");
        }
        if (!this.unit.equals(capacity.getUnit())) {
            throw new IllegalArgumentException("Units must be the same to compare WasteDemand and Capacity");
        }
        return this.value > capacity.getValue();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value, unit);
    }

    @Override
    public String toString() {
        return String.format("WasteDemand={value=%s, unit='%s'}", value, unit);
    }
}