package es.ull.project.adapter.rest.response.container;

import java.util.UUID;

/**
 * Data Transfer Object representing a Container response
 * This class is used to send Container data in HTTP responses
 * It contains all the data of a container in a structured format
 */
public class ContainerResponseBody {

    /**
     * Unique identifier of the container
     */
    public UUID id;

    /**
     * Physical location of the container
     */
    public LocationData location;

    /**
     * Type of waste collected by the container
     */
    public String wasteType;

    /**
     * Expected waste demand generated by the container
     */
    public WasteDemandData wasteDemand;

    /**
     * Service zone where the container is located
     * This field is optional
     */
    public String serviceZone;

    /**
     * Data structure for location information
     */
    public static class LocationData {
        /**
         * Latitude coordinate
         */
        public double latitude;

        /**
         * Longitude coordinate
         */
        public double longitude;

        /**
         * Postal address
         * This field is optional
         */
        public String postalAddress;

        /**
         * GIS reference identifier
         * This field is optional
         */
        public String gisReference;
    }

    /**
     * Data structure for waste demand information
     */
    public static class WasteDemandData {
        /**
         * Numeric value of the waste demand
         */
        public double value;

        /**
         * Unit of quantity (e.g., kg, tons, liters)
         */
        public String quantityUnit;

        /**
         * Time unit (e.g., DAYS, HOURS)
         */
        public String timeUnit;
    }
}
