package com.ull.domain.entity;

import com.ull.domain.enumerate.WasteType;
import com.ull.domain.valueobject.location.Location;
import java.util.Objects;
import java.util.UUID;

/**
 * Container entity used by the algorithm module.
 *
 * This is a simplified version of the backend container entity. It keeps
 * location as a dedicated value object and uses primitive values for the rest
 * of the attributes, except for waste type which remains an enum.
 */
public class Container {

  public static final String ID_NOT_DEFINED = "Container id is not defined";
  public static final String LOCATION_NOT_DEFINED = "Container location is not defined";
  public static final String WASTE_TYPE_NOT_DEFINED = "Waste type is not defined";
  public static final String CAPACITY_LITERS_NOT_DEFINED = "Container capacity in liters is not defined";
  public static final String DAILY_DEMAND_LITERS_NOT_DEFINED = "Daily waste demand in liters per day is not defined";
  public static final String CURRENT_LITERS_NOT_VALID = "Current liters is not valid";
  public static final String CURRENT_LITERS_EXCEEDED = "Current liters exceeds container capacity";

  private final String id;
  private Location location;
  private WasteType wasteType;
  private double capacityLiters;
  private double dailyDemandLitersPerDay;
  private String serviceZone;
  private double currentLiters;

  /**
   * Creates a container with an autogenerated identifier.
   *
   * @param location the container location
   * @param wasteType the waste type collected by the container
   * @param capacityLiters the capacity in liters
   * @param dailyDemandLitersPerDay the daily demand in liters per day
   * @param serviceZone the service zone
   */
  public Container(
      Location location,
      WasteType wasteType,
      double capacityLiters,
      double dailyDemandLitersPerDay,
      String serviceZone) {
    this(
        UUID.randomUUID().toString(),
        location,
        wasteType,
        capacityLiters,
        dailyDemandLitersPerDay,
        serviceZone);
  }

  /**
   * Creates a container without a service zone.
   *
   * @param location the container location
   * @param wasteType the waste type collected by the container
   * @param capacityLiters the capacity in liters
   * @param dailyDemandLitersPerDay the daily demand in liters per day
   */
  public Container(
      Location location,
      WasteType wasteType,
      double capacityLiters,
      double dailyDemandLitersPerDay) {
    this(location, wasteType, capacityLiters, dailyDemandLitersPerDay, null);
  }

  /**
   * Copy constructor.
   *
   * @param otherObject the container to copy
   */
  public Container(Container otherObject) {
    this(
        otherObject.id,
        otherObject.location,
        otherObject.wasteType,
        otherObject.capacityLiters,
        otherObject.dailyDemandLitersPerDay,
        otherObject.serviceZone);
  }

  /**
   * Restores a container with all its attributes.
   *
   * @param id the container identifier
   * @param location the container location
   * @param wasteType the waste type collected by the container
   * @param capacityLiters the capacity in liters
   * @param dailyDemandLitersPerDay the daily demand in liters per day
   * @param serviceZone the service zone
   */
  public Container(
      String id,
      Location location,
      WasteType wasteType,
      double capacityLiters,
      double dailyDemandLitersPerDay,
      String serviceZone) {
    validateId(id);
    validateLocation(location);
    validateWasteType(wasteType);
    validateCapacityLiters(capacityLiters);
    validateDailyDemandLitersPerDay(dailyDemandLitersPerDay);
    this.id = id;
    this.location = location;
    this.wasteType = wasteType;
    this.capacityLiters = capacityLiters;
    this.dailyDemandLitersPerDay = dailyDemandLitersPerDay;
    this.serviceZone = serviceZone;
    this.currentLiters = 0.0;
  }

  private void validateId(String id) {
    if (id == null || id.isBlank()) {
      throw new IllegalArgumentException(ID_NOT_DEFINED);
    }
  }

  private void validateLocation(Location location) {
    if (location == null) {
      throw new IllegalArgumentException(LOCATION_NOT_DEFINED);
    }
  }

  private void validateWasteType(WasteType wasteType) {
    if (wasteType == null) {
      throw new IllegalArgumentException(WASTE_TYPE_NOT_DEFINED);
    }
  }

  private void validateCapacityLiters(double capacityLiters) {
    if (capacityLiters < 0) {
      throw new IllegalArgumentException(CAPACITY_LITERS_NOT_DEFINED);
    }
  }

  private void validateDailyDemandLitersPerDay(double dailyDemandLitersPerDay) {
    if (dailyDemandLitersPerDay < 0) {
      throw new IllegalArgumentException(DAILY_DEMAND_LITERS_NOT_DEFINED);
    }
  }

  private void validateCurrentLiters(double currentLiters) {
    if (currentLiters < 0) {
      throw new IllegalArgumentException(CURRENT_LITERS_NOT_VALID);
    }
    if (currentLiters > this.capacityLiters) {
      throw new IllegalArgumentException(CURRENT_LITERS_EXCEEDED);
    }
  }

  public String getId() {
    return this.id;
  }

  public Location getLocation() {
    return this.location;
  }

  public void updateLocation(Location location) {
    validateLocation(location);
    this.location = location;
  }

  public WasteType getWasteType() {
    return this.wasteType;
  }

  public void updateWasteType(WasteType wasteType) {
    validateWasteType(wasteType);
    this.wasteType = wasteType;
  }

  public double getCapacityLiters() {
    return this.capacityLiters;
  }

  public void updateCapacityLiters(double capacityLiters) {
    validateCapacityLiters(capacityLiters);
    if (this.currentLiters > capacityLiters) {
      throw new IllegalArgumentException(CURRENT_LITERS_EXCEEDED);
    }
    this.capacityLiters = capacityLiters;
  }

  public double getDailyDemandLitersPerDay() {
    return this.dailyDemandLitersPerDay;
  }

  public void updateDailyDemandLitersPerDay(double dailyDemandLitersPerDay) {
    validateDailyDemandLitersPerDay(dailyDemandLitersPerDay);
    this.dailyDemandLitersPerDay = dailyDemandLitersPerDay;
  }

  public String getServiceZone() {
    return this.serviceZone;
  }

  public void updateServiceZone(String serviceZone) {
    this.serviceZone = serviceZone;
  }

  public double getCurrentLiters() {
    return this.currentLiters;
  }

  public void updateCurrentLiters(double currentLiters) {
    validateCurrentLiters(currentLiters);
    this.currentLiters = currentLiters;
  }

  public void addCurrentLiters(double litersToAdd) {
    updateCurrentLiters(this.currentLiters + litersToAdd);
  }

  public void removeCurrentLiters(double litersToRemove) {
    updateCurrentLiters(this.currentLiters - litersToRemove);
  }

  public void emptyCurrentLiters() {
    this.currentLiters = 0.0;
  }

  /**
   * Calculates the distance in meters to another container.
   *
   * @param otherContainer the target container
   * @return the distance in meters
   */
  public double calculateDistanceTo(Container otherContainer) {
    Objects.requireNonNull(otherContainer, "Other container cannot be null");
    return this.location.calculateDistanceTo(otherContainer.location);
  }

  /**
   * Calculates the distance in meters to a facility.
   *
   * @param facility the target facility
   * @return the distance in meters
   */
  public double calculateDistanceTo(Facility facility) {
    Objects.requireNonNull(facility, "Facility cannot be null");
    return this.location.calculateDistanceTo(facility.getLocation());
  }

  @Override
  public boolean equals(Object otherObject) {
    if (this == otherObject) {
      return true;
    }
    if (otherObject == null || getClass() != otherObject.getClass()) {
      return false;
    }
    Container otherContainer = (Container) otherObject;
    return Objects.equals(this.id, otherContainer.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.id);
  }

  @Override
  public String toString() {
    return String.format(
        "Container{id=%s, location=%s, wasteType=%s, capacityLiters=%s, dailyDemandLitersPerDay=%s, serviceZone=%s}",
        this.id,
        this.location,
        this.wasteType,
        this.capacityLiters,
        this.dailyDemandLitersPerDay,
        this.serviceZone);
  }
}
