package com.ull.domain.entity;

import com.ull.domain.enumerate.WasteType;
import com.ull.domain.valueobject.location.Location;
import java.util.Objects;
import java.util.UUID;

/**
 * Container entity used by the algorithm module.
 *
 * This is a simplified version of the backend container entity. It keeps
 * location as a dedicated value object and uses primitive values for the rest
 * of the attributes, except for waste type which remains an enum.
 */
public class Container {

  public static final String ID_NOT_DEFINED = "Container id is not defined";
  public static final String LOCATION_NOT_DEFINED = "Container location is not defined";
  public static final String WASTE_TYPE_NOT_DEFINED = "Waste type is not defined";
  public static final String CAPACITY_LITERS_NOT_DEFINED = "Container capacity in liters is not defined";
  public static final String DAILY_DEMAND_LITERS_NOT_DEFINED = "Daily waste demand in liters per day is not defined";
  public static final String CURRENT_LITERS_NOT_VALID = "Current liters is not valid";
  public static final String CURRENT_LITERS_EXCEEDED = "Current liters exceeds container capacity";
  public static final String FACILITY_NOT_DEFINED = "Facility cannot be null";
  public static final String OTHER_CONTAINER_NOT_DEFINED = "Other container cannot be null";
  private static final double ZERO_LITERS = 0.0;

  private final String id;
  private Location location;
  private WasteType wasteType;
  private double capacityLiters;
  private double dailyDemandLitersPerDay;
  private String serviceZone;
  private double currentLiters;

  /**
   * Creates a container with an autogenerated identifier.
   *
   * @param location the container location
   * @param wasteType the waste type collected by the container
   * @param capacityLiters the capacity in liters
   * @param dailyDemandLitersPerDay the daily demand in liters per day
   * @param serviceZone the service zone
   */
  public Container(
      Location location,
      WasteType wasteType,
      double capacityLiters,
      double dailyDemandLitersPerDay,
      String serviceZone) {
    this(
        UUID.randomUUID().toString(),
        location,
        wasteType,
        capacityLiters,
        dailyDemandLitersPerDay,
        serviceZone);
  }

  /**
   * Creates a container without a service zone.
   *
   * @param location the container location
   * @param wasteType the waste type collected by the container
   * @param capacityLiters the capacity in liters
   * @param dailyDemandLitersPerDay the daily demand in liters per day
   */
  public Container(
      Location location,
      WasteType wasteType,
      double capacityLiters,
      double dailyDemandLitersPerDay) {
    this(location, wasteType, capacityLiters, dailyDemandLitersPerDay, null);
  }

  /**
   * Copy constructor.
   *
   * @param otherObject the container to copy
   */
  public Container(Container otherObject) {
    this(
        otherObject.id,
        otherObject.location,
        otherObject.wasteType,
        otherObject.capacityLiters,
        otherObject.dailyDemandLitersPerDay,
        otherObject.serviceZone);
  }

  /**
   * Restores a container with all its attributes.
   *
   * @param id the container identifier
   * @param location the container location
   * @param wasteType the waste type collected by the container
   * @param capacityLiters the capacity in liters
   * @param dailyDemandLitersPerDay the daily demand in liters per day
   * @param serviceZone the service zone
   */
  public Container(
      String id,
      Location location,
      WasteType wasteType,
      double capacityLiters,
      double dailyDemandLitersPerDay,
      String serviceZone) {
    validateId(id);
    validateLocation(location);
    validateWasteType(wasteType);
    validateCapacityLiters(capacityLiters);
    validateDailyDemandLitersPerDay(dailyDemandLitersPerDay);
    this.id = id;
    this.location = location;
    this.wasteType = wasteType;
    this.capacityLiters = capacityLiters;
    this.dailyDemandLitersPerDay = dailyDemandLitersPerDay;
    this.serviceZone = serviceZone;
    this.currentLiters = ZERO_LITERS;
  }

  /**
   * Validates that the container identifier is present.
   *
   * @param id identifier to validate
   */
  private void validateId(String id) {
    if (id == null || id.isBlank()) {
      throw new IllegalArgumentException(ID_NOT_DEFINED);
    }
  }

  /**
   * Validates that the container location is present.
   *
   * @param location location to validate
   */
  private void validateLocation(Location location) {
    if (location == null) {
      throw new IllegalArgumentException(LOCATION_NOT_DEFINED);
    }
  }

  /**
   * Validates that the waste type is present.
   *
   * @param wasteType waste type to validate
   */
  private void validateWasteType(WasteType wasteType) {
    if (wasteType == null) {
      throw new IllegalArgumentException(WASTE_TYPE_NOT_DEFINED);
    }
  }

  /**
   * Validates that capacity in liters is not negative.
   *
   * @param capacityLiters capacity to validate
   */
  private void validateCapacityLiters(double capacityLiters) {
    if (capacityLiters < ZERO_LITERS) {
      throw new IllegalArgumentException(CAPACITY_LITERS_NOT_DEFINED);
    }
  }

  /**
   * Validates that daily demand in liters is not negative.
   *
   * @param dailyDemandLitersPerDay daily demand to validate
   */
  private void validateDailyDemandLitersPerDay(double dailyDemandLitersPerDay) {
    if (dailyDemandLitersPerDay < ZERO_LITERS) {
      throw new IllegalArgumentException(DAILY_DEMAND_LITERS_NOT_DEFINED);
    }
  }

  /**
   * Validates that current liters are within container capacity.
   *
   * @param currentLiters current liters to validate
   */
  private void validateCurrentLiters(double currentLiters) {
    if (currentLiters < ZERO_LITERS) {
      throw new IllegalArgumentException(CURRENT_LITERS_NOT_VALID);
    }
    if (currentLiters > this.capacityLiters) {
      throw new IllegalArgumentException(CURRENT_LITERS_EXCEEDED);
    }
  }

  /**
   * Returns the container identifier.
   *
   * @return container identifier
   */
  public String getId() {
    return this.id;
  }

  /**
   * Returns the container location.
   *
   * @return container location
   */
  public Location getLocation() {
    return this.location;
  }

  /**
   * Updates the container location.
   *
   * @param location new container location
   */
  public void updateLocation(Location location) {
    validateLocation(location);
    this.location = location;
  }

  /**
   * Returns the container waste type.
   *
   * @return waste type
   */
  public WasteType getWasteType() {
    return this.wasteType;
  }

  /**
   * Updates the container waste type.
   *
   * @param wasteType new waste type
   */
  public void updateWasteType(WasteType wasteType) {
    validateWasteType(wasteType);
    this.wasteType = wasteType;
  }

  /**
   * Returns the container capacity in liters.
   *
   * @return capacity in liters
   */
  public double getCapacityLiters() {
    return this.capacityLiters;
  }

  /**
   * Updates the container capacity in liters.
   *
   * @param capacityLiters new capacity in liters
   */
  public void updateCapacityLiters(double capacityLiters) {
    validateCapacityLiters(capacityLiters);
    if (this.currentLiters > capacityLiters) {
      throw new IllegalArgumentException(CURRENT_LITERS_EXCEEDED);
    }
    this.capacityLiters = capacityLiters;
  }

  /**
   * Returns the daily demand in liters per day.
   *
   * @return daily demand in liters per day
   */
  public double getDailyDemandLitersPerDay() {
    return this.dailyDemandLitersPerDay;
  }

  /**
   * Updates the daily demand in liters per day.
   *
   * @param dailyDemandLitersPerDay new daily demand
   */
  public void updateDailyDemandLitersPerDay(double dailyDemandLitersPerDay) {
    validateDailyDemandLitersPerDay(dailyDemandLitersPerDay);
    this.dailyDemandLitersPerDay = dailyDemandLitersPerDay;
  }

  /**
   * Returns the service zone.
   *
   * @return service zone, or null when not assigned
   */
  public String getServiceZone() {
    return this.serviceZone;
  }

  /**
   * Updates the service zone.
   *
   * @param serviceZone new service zone
   */
  public void updateServiceZone(String serviceZone) {
    this.serviceZone = serviceZone;
  }

  /**
   * Returns the current liters stored in the container.
   *
   * @return current liters
   */
  public double getCurrentLiters() {
    return this.currentLiters;
  }

  /**
   * Updates the current liters stored in the container.
   *
   * @param currentLiters new current liters
   */
  public void updateCurrentLiters(double currentLiters) {
    validateCurrentLiters(currentLiters);
    this.currentLiters = currentLiters;
  }

  /**
   * Adds liters to the current container filling.
   *
   * @param litersToAdd liters to add
   */
  public void addCurrentLiters(double litersToAdd) {
    updateCurrentLiters(this.currentLiters + litersToAdd);
  }

  /**
   * Removes liters from the current container filling.
   *
   * @param litersToRemove liters to remove
   */
  public void removeCurrentLiters(double litersToRemove) {
    updateCurrentLiters(this.currentLiters - litersToRemove);
  }

  /**
   * Empties the current container filling.
   */
  public void emptyCurrentLiters() {
    this.currentLiters = ZERO_LITERS;
  }

  /**
   * Calculates the distance in meters to another container.
   *
   * @param otherContainer the target container
   * @return the distance in meters
   */
  public double calculateDistanceTo(Container otherContainer) {
    Objects.requireNonNull(otherContainer, OTHER_CONTAINER_NOT_DEFINED);
    return this.location.calculateDistanceTo(otherContainer.location);
  }

  /**
   * Calculates the distance in meters to a facility.
   *
   * @param facility the target facility
   * @return the distance in meters
   */
  public double calculateDistanceTo(Facility facility) {
    Objects.requireNonNull(facility, FACILITY_NOT_DEFINED);
    return this.location.calculateDistanceTo(facility.getLocation());
  }

  /**
   * Compares this container with another object by identifier.
   *
   * @param otherObject object to compare
   * @return true when both containers share the same identifier
   */
  @Override
  public boolean equals(Object otherObject) {
    if (this == otherObject) {
      return true;
    }
    if (otherObject == null || getClass() != otherObject.getClass()) {
      return false;
    }
    Container otherContainer = (Container) otherObject;
    return Objects.equals(this.id, otherContainer.id);
  }

  /**
   * Returns a hash code based on the container identifier.
   *
   * @return hash code for this container
   */
  @Override
  public int hashCode() {
    return Objects.hash(this.id);
  }

  /**
   * Returns a readable representation of this container.
   *
   * @return text containing the main container attributes
   */
  @Override
  public String toString() {
    return String.format(
        "Container{id=%s, location=%s, wasteType=%s, capacityLiters=%s, dailyDemandLitersPerDay=%s, serviceZone=%s}",
        this.id,
        this.location,
        this.wasteType,
        this.capacityLiters,
        this.dailyDemandLitersPerDay,
        this.serviceZone);
  }
}
