package com.ull.domain.entity;

import com.ull.domain.valueobject.location.Location;
import java.util.Objects;
import java.util.UUID;

/**
 * Facility entity used by the algorithm module.
 *
 * This is a simplified version of the backend facility entity that keeps
 * complex concepts as primitive values except for location, which remains a
 * dedicated value object.
 */
public class Facility {

  public static final String ID_NOT_DEFINED = "Facility id is not defined";
  public static final String TYPE_NOT_DEFINED = "Facility type is not defined";
  public static final String LOCATION_NOT_DEFINED = "Facility location is not defined";
  public static final String STORAGE_CAPACITY_NOT_DEFINED = "Facility storage capacity is not defined";
  public static final String PROCESSING_CAPACITY_NOT_DEFINED = "Facility processing capacity is not defined";
  public static final String UNLOADING_TIME_NOT_DEFINED = "Facility unloading time is not defined";
  public static final String OPENING_COST_NOT_DEFINED = "Opening fixed cost is not defined";
  public static final String STATUS_NOT_DEFINED = "Facility status is not defined";
  public static final String CURRENT_FILLING_LEVEL_NOT_DEFINED = "Current filling level is not defined";
  public static final String CURRENT_STORED_KILOGRAMS_NOT_VALID = "Current stored kilograms is not valid";
  public static final String CURRENT_STORED_KILOGRAMS_EXCEEDED = "Current stored kilograms exceeds facility storage capacity";

  private final String id;
  private String facilityType;
  private Location location;
  private double storageCapacityKilograms;
  private double processingCapacityKilogramsPerDay;
  private int unloadingTimeMinutes;
  private double openingFixedCost;
  private String status;
  private double currentFillingLevel;
  private double currentStoredKilograms;

  /**
   * Creates a facility with an autogenerated identifier and zero filling level.
   *
   * @param facilityType the facility type
   * @param location the facility location
   * @param storageCapacityKilograms the storage capacity in kilograms
   * @param processingCapacityKilogramsPerDay the processing capacity in kilograms per day
   * @param unloadingTimeMinutes the unloading time in minutes
   * @param openingFixedCost the opening fixed cost
   * @param status the facility status
   */
  public Facility(
      String facilityType,
      Location location,
      double storageCapacityKilograms,
      double processingCapacityKilogramsPerDay,
      int unloadingTimeMinutes,
      double openingFixedCost,
      String status) {
    this(
        UUID.randomUUID().toString(),
        facilityType,
        location,
        storageCapacityKilograms,
        processingCapacityKilogramsPerDay,
        unloadingTimeMinutes,
        openingFixedCost,
        status,
        0.0);
  }

  /**
   * Copy constructor.
   *
   * @param otherObject the facility to copy
   */
  public Facility(Facility otherObject) {
    this(
        otherObject.id,
        otherObject.facilityType,
        otherObject.location,
        otherObject.storageCapacityKilograms,
        otherObject.processingCapacityKilogramsPerDay,
        otherObject.unloadingTimeMinutes,
        otherObject.openingFixedCost,
        otherObject.status,
        otherObject.currentFillingLevel);
  }

  /**
   * Restores a facility with all its attributes.
   *
   * @param id the facility identifier
   * @param facilityType the facility type
   * @param location the facility location
   * @param storageCapacityKilograms the storage capacity in kilograms
   * @param processingCapacityKilogramsPerDay the processing capacity in kilograms per day
   * @param unloadingTimeMinutes the unloading time in minutes
   * @param openingFixedCost the opening fixed cost
   * @param status the facility status
   * @param currentFillingLevel the current filling level
   */
  public Facility(
      String id,
      String facilityType,
      Location location,
      double storageCapacityKilograms,
      double processingCapacityKilogramsPerDay,
      int unloadingTimeMinutes,
      double openingFixedCost,
      String status,
      double currentFillingLevel) {
    validateId(id);
    validateFacilityType(facilityType);
    validateLocation(location);
    validateStorageCapacity(storageCapacityKilograms);
    validateProcessingCapacity(processingCapacityKilogramsPerDay);
    validateUnloadingTime(unloadingTimeMinutes);
    validateOpeningFixedCost(openingFixedCost);
    validateStatus(status);
    validateCurrentFillingLevel(currentFillingLevel);
    this.id = id;
    this.facilityType = facilityType;
    this.location = location;
    this.storageCapacityKilograms = storageCapacityKilograms;
    this.processingCapacityKilogramsPerDay = processingCapacityKilogramsPerDay;
    this.unloadingTimeMinutes = unloadingTimeMinutes;
    this.openingFixedCost = openingFixedCost;
    this.status = status;
    this.currentFillingLevel = currentFillingLevel;
    this.currentStoredKilograms = 0.0;
  }

  private void validateId(String id) {
    if (id == null || id.isBlank()) {
      throw new IllegalArgumentException(ID_NOT_DEFINED);
    }
  }

  private void validateFacilityType(String facilityType) {
    if (facilityType == null || facilityType.isBlank()) {
      throw new IllegalArgumentException(TYPE_NOT_DEFINED);
    }
  }

  private void validateLocation(Location location) {
    if (location == null) {
      throw new IllegalArgumentException(LOCATION_NOT_DEFINED);
    }
  }

  private void validateStorageCapacity(double storageCapacityKilograms) {
    if (storageCapacityKilograms < 0) {
      throw new IllegalArgumentException(STORAGE_CAPACITY_NOT_DEFINED);
    }
  }

  private void validateProcessingCapacity(double processingCapacityKilogramsPerDay) {
    if (processingCapacityKilogramsPerDay < 0) {
      throw new IllegalArgumentException(PROCESSING_CAPACITY_NOT_DEFINED);
    }
  }

  private void validateUnloadingTime(double unloadingTimeMinutes) {
    if (unloadingTimeMinutes < 0) {
      throw new IllegalArgumentException(UNLOADING_TIME_NOT_DEFINED);
    }
  }

  private void validateOpeningFixedCost(double openingFixedCost) {
    if (openingFixedCost < 0) {
      throw new IllegalArgumentException(OPENING_COST_NOT_DEFINED);
    }
  }

  private void validateStatus(String status) {
    if (status == null || status.isBlank()) {
      throw new IllegalArgumentException(STATUS_NOT_DEFINED);
    }
  }

  private void validateCurrentFillingLevel(double currentFillingLevel) {
    if (currentFillingLevel < 0) {
      throw new IllegalArgumentException(CURRENT_FILLING_LEVEL_NOT_DEFINED);
    }
  }

  private void validateCurrentStoredKilograms(double currentStoredKilograms) {
    if (currentStoredKilograms < 0) {
      throw new IllegalArgumentException(CURRENT_STORED_KILOGRAMS_NOT_VALID);
    }
    if (currentStoredKilograms > this.storageCapacityKilograms) {
      throw new IllegalArgumentException(CURRENT_STORED_KILOGRAMS_EXCEEDED);
    }
  }

  public String getId() {
    return this.id;
  }

  public String getFacilityType() {
    return this.facilityType;
  }

  public void updateFacilityType(String facilityType) {
    validateFacilityType(facilityType);
    this.facilityType = facilityType;
  }

  public Location getLocation() {
    return this.location;
  }

  public void updateLocation(Location location) {
    validateLocation(location);
    this.location = location;
  }

  public double getStorageCapacityKilograms() {
    return this.storageCapacityKilograms;
  }

  public void updateStorageCapacityKilograms(double storageCapacityKilograms) {
    validateStorageCapacity(storageCapacityKilograms);
    if (this.currentStoredKilograms > storageCapacityKilograms) {
      throw new IllegalArgumentException(CURRENT_STORED_KILOGRAMS_EXCEEDED);
    }
    this.storageCapacityKilograms = storageCapacityKilograms;
  }

  public double getProcessingCapacityKilogramsPerDay() {
    return this.processingCapacityKilogramsPerDay;
  }

  public void updateProcessingCapacityKilogramsPerDay(double processingCapacityKilogramsPerDay) {
    validateProcessingCapacity(processingCapacityKilogramsPerDay);
    this.processingCapacityKilogramsPerDay = processingCapacityKilogramsPerDay;
  }

  public double getUnloadingTimeMinutes() {
    return this.unloadingTimeMinutes;
  }

  public void updateUnloadingTimeMinutes(int unloadingTimeMinutes) {
    validateUnloadingTime(unloadingTimeMinutes);
    this.unloadingTimeMinutes = unloadingTimeMinutes;
  }

  public double getOpeningFixedCost() {
    return this.openingFixedCost;
  }

  public void updateOpeningFixedCost(double openingFixedCost) {
    validateOpeningFixedCost(openingFixedCost);
    this.openingFixedCost = openingFixedCost;
  }

  public String getStatus() {
    return this.status;
  }

  public void updateStatus(String status) {
    validateStatus(status);
    this.status = status;
  }

  public double getCurrentFillingLevel() {
    return this.currentFillingLevel;
  }

  public void updateCurrentFillingLevel(double currentFillingLevel) {
    validateCurrentFillingLevel(currentFillingLevel);
    this.currentFillingLevel = currentFillingLevel;
  }

  public double getCurrentStoredKilograms() {
    return this.currentStoredKilograms;
  }

  public void updateCurrentStoredKilograms(double currentStoredKilograms) {
    validateCurrentStoredKilograms(currentStoredKilograms);
    this.currentStoredKilograms = currentStoredKilograms;
  }

  public void addStoredKilograms(double kilogramsToAdd) {
    updateCurrentStoredKilograms(this.currentStoredKilograms + kilogramsToAdd);
  }

  public void removeStoredKilograms(double kilogramsToRemove) {
    updateCurrentStoredKilograms(this.currentStoredKilograms - kilogramsToRemove);
  }

  public void emptyStoredKilograms() {
    this.currentStoredKilograms = 0.0;
  }

  /**
   * Calculates the distance in meters to another facility using their
   * locations.
   *
   * @param otherFacility the target facility
   * @return the distance in meters
   */
  public double calculateDistanceTo(Facility otherFacility) {
    Objects.requireNonNull(otherFacility, "Other facility cannot be null");
    return this.location.calculateDistanceTo(otherFacility.location);
  }

  /**
   * Calculates the distance in meters to a container using their
   * locations.
   *
   * @param container the target container
   * @return the distance in meters
   */
  public double calculateDistanceTo(Container container) {
    Objects.requireNonNull(container, "Container cannot be null");
    return this.location.calculateDistanceTo(container.getLocation());
  }

  @Override
  public boolean equals(Object otherObject) {
    if (this == otherObject) {
      return true;
    }
    if (otherObject == null || getClass() != otherObject.getClass()) {
      return false;
    }
    Facility otherFacility = (Facility) otherObject;
    return Objects.equals(this.id, otherFacility.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.id);
  }

  @Override
  public String toString() {
    return String.format(
        "Facility{id=%s, facilityType=%s, location=%s, storageCapacityKilograms=%s, processingCapacityKilogramsPerDay=%s, unloadingTimeMinutes=%s, openingFixedCost=%s, status=%s, currentFillingLevel=%s}",
        this.id,
        this.facilityType,
        this.location,
        this.storageCapacityKilograms,
        this.processingCapacityKilogramsPerDay,
        this.unloadingTimeMinutes,
        this.openingFixedCost,
        this.status,
        this.currentFillingLevel);
  }
}
