package com.ull.domain.entity;

import com.ull.domain.enumerate.WasteType;
import java.util.Objects;
import java.util.UUID;

/**
 * Vehicle entity used by the algorithm module.
 *
 * This is a simplified version of the backend vehicle entity that replaces
 * value objects and enums with primitive values to keep the algorithm model
 * lightweight.
 */
public class Vehicle {

  public static final String ID_NOT_DEFINED = "Vehicle id is not defined";
  public static final String TYPE_NOT_DEFINED = "Vehicle type is not defined";
  public static final String CAPACITY_KILOGRAMS_NOT_DEFINED = "Vehicle capacity in kilograms is not defined";
  public static final String CAPACITY_LITERS_NOT_DEFINED = "Vehicle capacity in liters is not defined";
  public static final String COST_NOT_DEFINED = "Transportation variable cost is not defined";
  public static final String CURRENT_LOAD_KILOGRAMS_NOT_VALID = "Current load in kilograms is not valid";
  public static final String CURRENT_LOAD_LITERS_NOT_VALID = "Current load in liters is not valid";
  public static final String CURRENT_LOAD_KILOGRAMS_EXCEEDED = "Current load in kilograms exceeds vehicle capacity";
  public static final String CURRENT_LOAD_LITERS_EXCEEDED = "Current load in liters exceeds vehicle capacity";

  private final String id;
  private String vehicleType;
  private double capacityKilograms;
  private double capacityLiters;
  private double costPerKilometer;
  private WasteType currentWasteType;
  private double currentLoadKilograms;
  private double currentLoadLiters;

  /**
   * Creates a vehicle with an autogenerated identifier.
   *
   * @param vehicleType the vehicle type
   * @param capacityKilograms the vehicle capacity in kilograms
   * @param capacityLiters the vehicle capacity in liters
   * @param costPerKilometer the vehicle operating cost per kilometer
   */
  public Vehicle(
      String vehicleType,
      double capacityKilograms,
      double capacityLiters,
      double costPerKilometer) {
    this(UUID.randomUUID().toString(), vehicleType, capacityKilograms, capacityLiters, costPerKilometer);
  }

  /**
   * Copy constructor.
   *
   * @param otherObject the vehicle to copy
   */
  public Vehicle(Vehicle otherObject) {
    this(
        otherObject.id,
        otherObject.vehicleType,
        otherObject.capacityKilograms,
        otherObject.capacityLiters,
        otherObject.costPerKilometer);
  }

  /**
   * Restores a vehicle with all its attributes.
   *
   * @param id the vehicle identifier
   * @param vehicleType the vehicle type
   * @param capacityKilograms the vehicle capacity in kilograms
   * @param capacityLiters the vehicle capacity in liters
   * @param costPerKilometer the vehicle operating cost per kilometer
   */
  public Vehicle(
      String id,
      String vehicleType,
      double capacityKilograms,
      double capacityLiters,
      double costPerKilometer) {
    validateId(id);
    validateVehicleType(vehicleType);
    validateCapacityKilograms(capacityKilograms);
    validateCapacityLiters(capacityLiters);
    validateCost(costPerKilometer);
    this.id = id;
    this.vehicleType = vehicleType;
    this.capacityKilograms = capacityKilograms;
    this.capacityLiters = capacityLiters;
    this.costPerKilometer = costPerKilometer;
    this.currentWasteType = null;
    this.currentLoadKilograms = 0.0;
    this.currentLoadLiters = 0.0;
  }

  private void validateId(String id) {
    if (id == null || id.isBlank()) {
      throw new IllegalArgumentException(ID_NOT_DEFINED);
    }
  }

  private void validateVehicleType(String type) {
    if (type == null || type.isBlank()) {
      throw new IllegalArgumentException(TYPE_NOT_DEFINED);
    }
  }

  private void validateCapacityKilograms(double capacity) {
    if (capacity < 0) {
      throw new IllegalArgumentException(CAPACITY_KILOGRAMS_NOT_DEFINED);
    }
  }

  private void validateCapacityLiters(double capacity) {
    if (capacity < 0) {
      throw new IllegalArgumentException(CAPACITY_LITERS_NOT_DEFINED);
    }
  }

  private void validateCost(double cost) {
    if (cost < 0) {
      throw new IllegalArgumentException(COST_NOT_DEFINED);
    }
  }

  private void validateCurrentLoadKilograms(double currentLoadKilograms) {
    if (currentLoadKilograms < 0) {
      throw new IllegalArgumentException(CURRENT_LOAD_KILOGRAMS_NOT_VALID);
    }
    if (currentLoadKilograms > this.capacityKilograms) {
      throw new IllegalArgumentException(CURRENT_LOAD_KILOGRAMS_EXCEEDED);
    }
  }

  private void validateCurrentLoadLiters(double currentLoadLiters) {
    if (currentLoadLiters < 0) {
      throw new IllegalArgumentException(CURRENT_LOAD_LITERS_NOT_VALID);
    }
    if (currentLoadLiters > this.capacityLiters) {
      throw new IllegalArgumentException(CURRENT_LOAD_LITERS_EXCEEDED);
    }
  }

  public String getId() {
    return this.id;
  }

  public String getVehicleType() {
    return this.vehicleType;
  }

  public void updateVehicleType(String vehicleType) {
    validateVehicleType(vehicleType);
    this.vehicleType = vehicleType;
  }

  public double getCapacityKilograms() {
    return this.capacityKilograms;
  }

  public void updateCapacityKilograms(double capacityKilograms) {
    validateCapacityKilograms(capacityKilograms);
    if (this.currentLoadKilograms > capacityKilograms) {
      throw new IllegalArgumentException(CURRENT_LOAD_KILOGRAMS_EXCEEDED);
    }
    this.capacityKilograms = capacityKilograms;
  }

  public double getCapacityLiters() {
    return this.capacityLiters;
  }

  public void updateCapacityLiters(double capacityLiters) {
    validateCapacityLiters(capacityLiters);
    if (this.currentLoadLiters > capacityLiters) {
      throw new IllegalArgumentException(CURRENT_LOAD_LITERS_EXCEEDED);
    }
    this.capacityLiters = capacityLiters;
  }

  public double getCostPerKilometer() {
    return this.costPerKilometer;
  }

  public void updateCostPerKilometer(double costPerKilometer) {
    validateCost(costPerKilometer);
    this.costPerKilometer = costPerKilometer;
  }

  public WasteType getCurrentWasteType() {
    return this.currentWasteType;
  }

  public void updateCurrentWasteType(WasteType currentWasteType) {
    this.currentWasteType = currentWasteType;
  }

  public double getCurrentLoadKilograms() {
    return this.currentLoadKilograms;
  }

  public void updateCurrentLoadKilograms(double currentLoadKilograms) {
    validateCurrentLoadKilograms(currentLoadKilograms);
    this.currentLoadKilograms = currentLoadKilograms;
  }

  public void addLoadKilograms(double kilogramsToAdd) {
    updateCurrentLoadKilograms(this.currentLoadKilograms + kilogramsToAdd);
  }

  public void removeLoadKilograms(double kilogramsToRemove) {
    updateCurrentLoadKilograms(this.currentLoadKilograms - kilogramsToRemove);
  }

  public void emptyLoadKilograms() {
    this.currentLoadKilograms = 0.0;
  }

  public double getCurrentLoadLiters() {
    return this.currentLoadLiters;
  }

  public void updateCurrentLoadLiters(double currentLoadLiters) {
    validateCurrentLoadLiters(currentLoadLiters);
    this.currentLoadLiters = currentLoadLiters;
  }

  public void addLoadLiters(double litersToAdd) {
    updateCurrentLoadLiters(this.currentLoadLiters + litersToAdd);
  }

  public void removeLoadLiters(double litersToRemove) {
    updateCurrentLoadLiters(this.currentLoadLiters - litersToRemove);
  }

  public void emptyLoadLiters() {
    this.currentLoadLiters = 0.0;
  }

  public void emptyLoad() {
    this.currentWasteType = null;
    emptyLoadKilograms();
    emptyLoadLiters();
  }

  @Override
  public boolean equals(Object otherObject) {
    if (this == otherObject) {
      return true;
    }
    if (otherObject == null || getClass() != otherObject.getClass()) {
      return false;
    }
    Vehicle otherVehicle = (Vehicle) otherObject;
    return Objects.equals(this.id, otherVehicle.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.id);
  }

  @Override
  public String toString() {
    return String.format(
        "Vehicle{id=%s, vehicleType=%s, capacityKilograms=%s, capacityLiters=%s, costPerKilometer=%s}",
        this.id,
        this.vehicleType,
        this.capacityKilograms,
        this.capacityLiters,
        this.costPerKilometer);
  }
}
