package es.ull.project.domain.entity;

import java.util.Objects;
import java.util.Optional;

import es.ull.project.domain.valueobject.identifiers.ContainerId;
import es.ull.project.domain.valueobject.location.Location;
import es.ull.project.domain.valueobject.demand.WasteDemand;
import es.ull.project.domain.valueobject.clasification.WasteType;
import es.ull.project.domain.valueobject.clasification.ServiceZone;

/**
 * Container
 *
 * Represents a physical waste collection point
 * (street container, drop-off point, etc.).
 */
public class Container {

    public static final String ID_NOT_DEFINED = "Container id is not defined";
    public static final String LOCATION_NOT_DEFINED = "Container location is not defined";
    public static final String WASTE_TYPE_NOT_DEFINED = "Waste type is not defined";
    public static final String WASTE_DEMAND_NOT_DEFINED = "Waste demand is not defined";

    /**
     * Identifier of the container.
     * It is a required and immutable attribute.
     */
    private final ContainerId id;

    /**
     * Physical location of the container.
     * It is a required attribute.
     */
    private Location location;

    /**
     * Waste type collected by the container.
     * It is a required attribute.
     */
    private WasteType wasteType;

    /**
     * Expected waste demand generated by the container.
     * It is a required attribute.
     */
    private WasteDemand wasteDemand;

    /**
     * Service zone where the container is located.
     * It is an optional attribute.
     */
    private ServiceZone serviceZone;

    /**
     * Creates a new Container.
     *
     * @param id           Container identifier.
     * @param location     Location of the container.
     * @param wasteType    Type of waste collected.
     * @param wasteDemand  Waste demand.
     * @param serviceZone  Service zone (optional).
     */
    public Container(ContainerId id,
                     Location location,
                     WasteType wasteType,
                     WasteDemand wasteDemand,
                     ServiceZone serviceZone) {

        this.validateId(id);
        this.validateLocation(location);
        this.validateWasteType(wasteType);
        this.validateWasteDemand(wasteDemand);

        this.id = id;
        this.location = location;
        this.wasteType = wasteType;
        this.wasteDemand = wasteDemand;
        this.serviceZone = serviceZone;
    }

    /**
     * Creates a new Container without a service zone.
     *
     * @param id           Container identifier.
     * @param location     Location of the container.
     * @param wasteType    Type of waste collected.
     * @param wasteDemand  Waste demand.
     */
    public Container(ContainerId id,
                     Location location,
                     WasteType wasteType,
                     WasteDemand wasteDemand) {

        this(id, location, wasteType, wasteDemand, null);
    }

    private void validateId(ContainerId id) {
        if (id == null) {
            throw new IllegalArgumentException(ID_NOT_DEFINED);
        }
    }

    private void validateLocation(Location location) {
        if (location == null) {
            throw new IllegalArgumentException(LOCATION_NOT_DEFINED);
        }
    }

    private void validateWasteType(WasteType wasteType) {
        if (wasteType == null) {
            throw new IllegalArgumentException(WASTE_TYPE_NOT_DEFINED);
        }
    }

    private void validateWasteDemand(WasteDemand wasteDemand) {
        if (wasteDemand == null) {
            throw new IllegalArgumentException(WASTE_DEMAND_NOT_DEFINED);
        }
    }

    /**
     * Returns the container identifier.
     *
     * @return ContainerId.
     */
    public ContainerId getId() {
        return this.id;
    }

    /**
     * Returns the container location.
     *
     * @return Location.
     */
    public Location getLocation() {
        return this.location;
    }

    /**
     * Updates the container location.
     *
     * @param location New location.
     */
    public void updateLocation(Location location) {
        this.validateLocation(location);
        this.location = location;
    }

    /**
     * Returns the waste type of the container.
     *
     * @return WasteType.
     */
    public WasteType getWasteType() {
        return this.wasteType;
    }

    /**
     * Updates the waste type of the container.
     *
     * @param wasteType New waste type.
     */
    public void updateWasteType(WasteType wasteType) {
        this.validateWasteType(wasteType);
        this.wasteType = wasteType;
    }

    /**
     * Returns the waste demand.
     *
     * @return WasteDemand.
     */
    public WasteDemand getWasteDemand() {
        return this.wasteDemand;
    }

    /**
     * Updates the waste demand.
     *
     * @param wasteDemand New waste demand.
     */
    public void updateWasteDemand(WasteDemand wasteDemand) {
        this.validateWasteDemand(wasteDemand);
        this.wasteDemand = wasteDemand;
    }

    /**
     * Returns the service zone, if defined.
     *
     * @return Optional ServiceZone.
     */
    public Optional<ServiceZone> getServiceZone() {
        return Optional.ofNullable(this.serviceZone);
    }

    /**
     * Updates the service zone.
     *
     * @param serviceZone New service zone.
     */
    public void updateServiceZone(ServiceZone serviceZone) {
        this.serviceZone = serviceZone;
    }

    @Override
    public boolean equals(Object otherObject) {
        if (this == otherObject) {
            return true;
        }
        if (otherObject == null) {
            return false;
        }
        if (getClass() != otherObject.getClass()) {
            return false;
        }
        final Container other = (Container) otherObject;
        return Objects.equals(this.id, other.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.id);
    }

    @Override
    public String toString() {
        return String.format(
                "Container={id=%s, location=%s, wasteType=%s, wasteDemand=%s, serviceZone=%s}",
                this.id,
                this.location,
                this.wasteType,
                this.wasteDemand,
                this.serviceZone
        );
    }
}