package es.ull.project.domain.entity;

import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import es.ull.project.domain.enumerate.ServiceZone;
import es.ull.project.domain.enumerate.WasteType;
import es.ull.project.domain.valueobject.demand.WasteDemand;
import es.ull.project.domain.valueobject.location.Location;

/**
 * Container
 *
 * Represents a physical waste collection point
 * (street container, drop-off point, etc.).
 */
public class Container {

    public static final String ID_NOT_DEFINED = "Container id is not defined";
    public static final String LOCATION_NOT_DEFINED = "Container location is not defined";
    public static final String WASTE_TYPE_NOT_DEFINED = "Waste type is not defined";
    public static final String WASTE_DEMAND_NOT_DEFINED = "Waste demand is not defined";

    /**
     * Identifier of the container.
     * It is a required and immutable attribute.
     */
    private final UUID  id;

    /**
     * Physical location of the container.
     * It is a required attribute.
     */
    private Location location;

    /**
     * Waste type collected by the container.
     * It is a required attribute.
     */
    private WasteType wasteType;

    /**
     * Expected waste demand generated by the container.
     * It is a required attribute.
     */
    private WasteDemand wasteDemand;

    /**
     * Service zone where the container is located.
     * It is an optional attribute.
     */
    private ServiceZone serviceZone;

    /**
     * Creates a new Container.
     *
     * @param id           Container identifier.
     * @param location     Location of the container.
     * @param wasteType    Type of waste collected.
     * @param wasteDemand  Waste demand.
     * @param serviceZone  Service zone (optional).
     */
    public Container(
                     Location location,
                     WasteType wasteType,
                     WasteDemand wasteDemand,
                     ServiceZone serviceZone) {
        this.validateLocation(location);
        this.validateWasteType(wasteType);
        this.validateWasteDemand(wasteDemand);
        this.id = UUID.randomUUID();
        this.location = location;
        this.wasteType = wasteType;
        this.wasteDemand = wasteDemand;
        this.serviceZone = serviceZone;
    }

    /**
     * Creates a new Container without a service zone.
     *
     * @param id           Container identifier.
     * @param location     Location of the container.
     * @param wasteType    Type of waste collected.
     * @param wasteDemand  Waste demand.
     */
    public Container(
                     Location location,
                     WasteType wasteType,
                     WasteDemand wasteDemand) {
        this(location, wasteType, wasteDemand, null);
    }

    /**
     * Copy constructor.
     * Creates a new Container as a copy of another Container.
     *
     * @param otherObject the Container to copy
     */
    public Container(Container otherObject) {
        this.id = otherObject.id;
        this.location = otherObject.location;
        this.wasteType = otherObject.wasteType;
        this.wasteDemand = otherObject.wasteDemand;
        this.serviceZone = otherObject.serviceZone;
    }

    /**
     * Restore constructor.
     * Restores a Container from persistence with all its attributes.
     *
     * @param id           the container identifier
     * @param location     the location of the container
     * @param wasteType    the type of waste collected
     * @param wasteDemand  the waste demand
     * @param serviceZone  the service zone (optional)
     */
    public Container(UUID id,
                     Location location,
                     WasteType wasteType,
                     WasteDemand wasteDemand,
                     ServiceZone serviceZone) {
        this.validateLocation(location);
        this.validateWasteType(wasteType);
        this.validateWasteDemand(wasteDemand);
        this.id = id;
        this.location = location;
        this.wasteType = wasteType;
        this.wasteDemand = wasteDemand;
        this.serviceZone = serviceZone;
    }

    /**
     * Validates that the location is not null.
     *
     * @param location the location to validate
     * @throws IllegalArgumentException if the location is null
     */
    private void validateLocation(Location location) {
        if (location == null) {
            throw new IllegalArgumentException(LOCATION_NOT_DEFINED);
        }
    }

    /**
     * Validates that the waste type is not null.
     *
     * @param wasteType the waste type to validate
     * @throws IllegalArgumentException if the waste type is null
     */
    private void validateWasteType(WasteType wasteType) {
        if (wasteType == null) {
            throw new IllegalArgumentException(WASTE_TYPE_NOT_DEFINED);
        }
    }

    /**
     * Validates that the waste demand is not null.
     *
     * @param wasteDemand the waste demand to validate
     * @throws IllegalArgumentException if the waste demand is null
     */
    private void validateWasteDemand(WasteDemand wasteDemand) {
        if (wasteDemand == null) {
            throw new IllegalArgumentException(WASTE_DEMAND_NOT_DEFINED);
        }
    }

    /**
     * Returns the container identifier.
     *
     * @return ContainerId.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Returns the container location.
     *
     * @return Location.
     */
    public Location getLocation() {
        return this.location;
    }

    /**
     * Updates the container location.
     *
     * @param location New location.
     */
    public void updateLocation(Location location) {
        this.validateLocation(location);
        this.location = location;
    }

    /**
     * Returns the waste type of the container.
     *
     * @return WasteType.
     */
    public WasteType getWasteType() {
        return this.wasteType;
    }

    /**
     * Updates the waste type of the container.
     *
     * @param wasteType New waste type.
     */
    public void updateWasteType(WasteType wasteType) {
        this.validateWasteType(wasteType);
        this.wasteType = wasteType;
    }

    /**
     * Returns the waste demand.
     *
     * @return WasteDemand.
     */
    public WasteDemand getWasteDemand() {
        return this.wasteDemand;
    }

    /**
     * Updates the waste demand.
     *
     * @param wasteDemand New waste demand.
     */
    public void updateWasteDemand(WasteDemand wasteDemand) {
        this.validateWasteDemand(wasteDemand);
        this.wasteDemand = wasteDemand;
    }

    /**
     * Returns the service zone, if defined.
     *
     * @return Optional ServiceZone.
     */
    public Optional<ServiceZone> getServiceZone() {
        return Optional.ofNullable(this.serviceZone);
    }

    /**
     * Updates the service zone.
     *
     * @param serviceZone New service zone.
     */
    public void updateServiceZone(ServiceZone serviceZone) {
        this.serviceZone = serviceZone;
    }

    /**
     * Compares this container to another object for equality.
     *
     * @param otherObject the object to compare with
     * @return true if the objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object otherObject) {
        if (this == otherObject) {
            return true;
        }
        if (otherObject == null) {
            return false;
        }
        if (getClass() != otherObject.getClass()) {
            return false;
        }
        final Container other = (Container) otherObject;
        return Objects.equals(this.id, other.id);
    }

    /**
     * Returns a hash code value for this container.
     *
     * @return a hash code value based on the container identifier
     */
    @Override
    public int hashCode() {
        return Objects.hash(this.id);
    }

    /**
     * Returns a string representation of this container.
     *
     * @return a formatted string containing all container attributes
     */
    @Override
    public String toString() {
        return String.format(
                "Container={id=%s, location=%s, wasteType=%s, wasteDemand=%s, serviceZone=%s}",
                this.id,
                this.location,
                this.wasteType,
                this.wasteDemand,
                this.serviceZone
        );
    }
}