package es.ull.project.domain.entity;

import java.util.Objects;
import java.util.Optional;
import java.util.UUID;

import es.ull.project.domain.enumerate.ServiceZone;
import es.ull.project.domain.enumerate.WasteType;
import es.ull.project.domain.valueobject.demand.ContainerCapacityLiters;
import es.ull.project.domain.valueobject.demand.DailyWasteDemandLitersPerDay;
import es.ull.project.domain.valueobject.location.Location;

/**
 * Container
 *
 * Represents a physical waste collection point
 * (street container, drop-off point, etc.).
 */
public class Container {

    public static final String ID_NOT_DEFINED = "Container id is not defined";
    public static final String LOCATION_NOT_DEFINED = "Container location is not defined";
    public static final String WASTE_TYPE_NOT_DEFINED = "Waste type is not defined";
    public static final String CAPACITY_LITERS_NOT_DEFINED = "Container capacity in liters is not defined";
    public static final String DAILY_DEMAND_LITERS_NOT_DEFINED = "Daily waste demand in liters is not defined";

    /**
     * Identifier of the container.
     * It is a required and immutable attribute.
     * It is a computed attribute.
     */
    private final UUID id;

    /**
     * Physical location of the container.
     * It is a required attribute.
     */
    private Location location;

    /**
     * Waste type collected by the container.
     * It is a required attribute.
     */
    private WasteType wasteType;

    /**
     * Maximum capacity of the container in liters.
     * It is a required attribute.
     */
    private ContainerCapacityLiters capacityLiters;

    /**
     * Approximate daily waste demand generated by the container in liters per day.
     * It is a required attribute.
     */
    private DailyWasteDemandLitersPerDay dailyDemandLitersPerDay;

    /**
     * Service zone where the container is located.
     * It is an optional attribute.
     */
    private ServiceZone serviceZone;

    /**
     * Creates a new Container.
     *
     * @param location    Location of the container.
     * @param wasteType   Type of waste collected.
     * @param capacityLiters Maximum capacity in liters.
     * @param dailyDemandLitersPerDay Approximate daily waste demand in liters per day.
     * @param serviceZone Service zone (optional).
     */
    public Container(
            Location location,
            WasteType wasteType,
            ContainerCapacityLiters capacityLiters,
            DailyWasteDemandLitersPerDay dailyDemandLitersPerDay,
            ServiceZone serviceZone) {
        this.validateLocation(location);
        this.validateWasteType(wasteType);
        this.validateCapacityLiters(capacityLiters);
        this.validateDailyDemandLitersPerDay(dailyDemandLitersPerDay);
        this.id = UUID.randomUUID();
        this.location = location;
        this.wasteType = wasteType;
        this.capacityLiters = capacityLiters;
        this.dailyDemandLitersPerDay = dailyDemandLitersPerDay;
        this.serviceZone = serviceZone;
    }

    /**
     * Creates a new Container without a service zone.
     *
     * @param location    Location of the container.
     * @param wasteType   Type of waste collected.
     * @param capacityLiters Maximum capacity in liters.
     * @param dailyDemandLitersPerDay Approximate daily waste demand in liters per day.
     */
    public Container(
            Location location,
            WasteType wasteType,
            ContainerCapacityLiters capacityLiters,
            DailyWasteDemandLitersPerDay dailyDemandLitersPerDay) {
        this(location, wasteType, capacityLiters, dailyDemandLitersPerDay, null);
    }

    /**
     * Copy constructor.
     * Creates a new Container as a copy of another Container.
     *
     * @param otherObject the Container to copy
     */
    public Container(Container otherObject) {
        this.id = otherObject.id;
        this.location = otherObject.location;
        this.wasteType = otherObject.wasteType;
        this.capacityLiters = otherObject.capacityLiters;
        this.dailyDemandLitersPerDay = otherObject.dailyDemandLitersPerDay;
        this.serviceZone = otherObject.serviceZone;
    }

    /**
     * Restore constructor.
     * Restores a Container from persistence with all its attributes.
     *
     * @param id          the container identifier
     * @param location    the location of the container
     * @param wasteType   the type of waste collected
     * @param capacityLiters the maximum capacity in liters
     * @param dailyDemandLitersPerDay the approximate daily waste demand in liters per day
     * @param serviceZone the service zone (optional)
     */
    public Container(UUID id,
            Location location,
            WasteType wasteType,
            ContainerCapacityLiters capacityLiters,
            DailyWasteDemandLitersPerDay dailyDemandLitersPerDay,
            ServiceZone serviceZone) {
        this.validateLocation(location);
        this.validateWasteType(wasteType);
        this.validateCapacityLiters(capacityLiters);
        this.validateDailyDemandLitersPerDay(dailyDemandLitersPerDay);
        this.id = id;
        this.location = location;
        this.wasteType = wasteType;
        this.capacityLiters = capacityLiters;
        this.dailyDemandLitersPerDay = dailyDemandLitersPerDay;
        this.serviceZone = serviceZone;
    }

    /**
     * Validates that the location is not null.
     *
     * @param location the location to validate
     * @throws IllegalArgumentException if the location is null
     */
    private void validateLocation(Location location) {
        if (location == null) {
            throw new IllegalArgumentException(LOCATION_NOT_DEFINED);
        }
    }

    /**
     * Validates that the waste type is not null.
     *
     * @param wasteType the waste type to validate
     * @throws IllegalArgumentException if the waste type is null
     */
    private void validateWasteType(WasteType wasteType) {
        if (wasteType == null) {
            throw new IllegalArgumentException(WASTE_TYPE_NOT_DEFINED);
        }
    }

    /**
     * Validates that the capacity in liters is not null.
     *
     * @param capacityLiters the capacity in liters to validate
     * @throws IllegalArgumentException if the capacity in liters is null
     */
    private void validateCapacityLiters(ContainerCapacityLiters capacityLiters) {
        if (capacityLiters == null) {
            throw new IllegalArgumentException(CAPACITY_LITERS_NOT_DEFINED);
        }
    }

    /**
     * Validates that the daily demand in liters per day is not null.
     *
     * @param dailyDemandLitersPerDay the daily demand in liters per day to validate
     * @throws IllegalArgumentException if the daily demand in liters per day is null
     */
    private void validateDailyDemandLitersPerDay(DailyWasteDemandLitersPerDay dailyDemandLitersPerDay) {
        if (dailyDemandLitersPerDay == null) {
            throw new IllegalArgumentException(DAILY_DEMAND_LITERS_NOT_DEFINED);
        }
    }

    /**
     * Returns the container identifier.
     *
     * @return ContainerId.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Returns the container location.
     *
     * @return Location.
     */
    public Location getLocation() {
        return this.location;
    }

    /**
     * Updates the container location.
     *
     * @param location New location.
     */
    public void updateLocation(Location location) {
        this.validateLocation(location);
        this.location = location;
    }

    /**
     * Returns the waste type of the container.
     *
     * @return WasteType.
     */
    public WasteType getWasteType() {
        return this.wasteType;
    }

    /**
     * Updates the waste type of the container.
     *
     * @param wasteType New waste type.
     */
    public void updateWasteType(WasteType wasteType) {
        this.validateWasteType(wasteType);
        this.wasteType = wasteType;
    }

    /**
     * Returns the service zone, if defined.
     *
     * @return Optional ServiceZone.
     */
    public Optional<ServiceZone> getServiceZone() {
        return Optional.ofNullable(this.serviceZone);
    }

    /**
     * Updates the service zone.
     *
     * @param serviceZone New service zone.
     */
    public void updateServiceZone(ServiceZone serviceZone) {
        this.serviceZone = serviceZone;
    }

    /**
     * Returns the container capacity in liters.
     *
     * @return ContainerCapacityLiters.
     */
    public ContainerCapacityLiters getCapacityLiters() {
        return this.capacityLiters;
    }

    /**
     * Updates the container capacity in liters.
     *
     * @param capacityLiters New capacity in liters.
     */
    public void updateCapacityLiters(ContainerCapacityLiters capacityLiters) {
        this.validateCapacityLiters(capacityLiters);
        this.capacityLiters = capacityLiters;
    }

    /**
     * Returns the approximate daily waste demand in liters per day.
     *
     * @return DailyWasteDemandLitersPerDay.
     */
    public DailyWasteDemandLitersPerDay getDailyDemandLitersPerDay() {
        return this.dailyDemandLitersPerDay;
    }

    /**
     * Updates the approximate daily waste demand in liters per day.
     *
     * @param dailyDemandLitersPerDay New daily demand in liters per day.
     */
    public void updateDailyDemandLitersPerDay(DailyWasteDemandLitersPerDay dailyDemandLitersPerDay) {
        this.validateDailyDemandLitersPerDay(dailyDemandLitersPerDay);
        this.dailyDemandLitersPerDay = dailyDemandLitersPerDay;
    }

    /**
     * Compares this container to another object for equality.
     *
     * @param otherObject the object to compare with
     * @return true if the objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object otherObject) {
        if (this == otherObject) {
            return true;
        }
        if (otherObject == null) {
            return false;
        }
        if (getClass() != otherObject.getClass()) {
            return false;
        }
        final Container other = (Container) otherObject;
        return Objects.equals(this.id, other.id);
    }

    /**
     * Returns a hash code value for this container.
     *
     * @return a hash code value based on the container identifier
     */
    @Override
    public int hashCode() {
        return Objects.hash(this.id);
    }

    /**
     * Returns a string representation of this container.
     *
     * @return a formatted string containing all container attributes
     */
    @Override
    public String toString() {
        return String.format(
                "Container={id=%s, location=%s, wasteType=%s, capacityLiters=%s, dailyDemandLitersPerDay=%s, serviceZone=%s}",
                this.id,
                this.location,
                this.wasteType,
                this.capacityLiters,
                this.dailyDemandLitersPerDay,
                this.serviceZone);
    }
}